### ISSUE TITLE
Allow to configure the google domain

### ISSUE THREAD

**Issue by imargonis** [satoryu/google_suggest#2]
Hi,
it would be nice if it would be possible to configure which google domain to use (change the 'com' part to something else). I have noticed the suggestion results are different depending on which google domain you use.

Thanks.

**Comment by satoryu** [comment]
Thank you for your request. your idea looks nice. 
btw, do you know a list of all google's domains?

**Comment by imargonis** [comment]
Thank you for considering this.

A quick search resulted in this https://en.wikipedia.org/wiki/List_of_Google_domains

**Comment by satoryu** [comment]
Hi, @imargonis 

sorry for tooooo late reply. today I have released the version of this gem 🎉 
I would like you to try it. so you can get new version by `gem update google_suggest` or, if you use bundler `bundle update google_suggest`.
